import { Navigation } from '@/components/Navigation'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-100 h-100 flex flex-col min-h-screen">
          <Navigation />
          <main>{children}</main>
          <footer className="container max-w-screen-lg mx-auto mt-auto">
            Footer
          </footer>
        </div>
      </body>
    </html>
  )
}
